[workspace]
members = [
    "exactapi",
    "proto",
    "client_library",
    "exact_filter",
    "exact_requests",
]

[profile.release]
strip = true

[patch.crates-io.typeshare]
git = "ssh://git@github.com/MrFriendly-B-V/typeshare"
branch = "support-64-typescript"