version: '3'
services:
  runner:
    container_name: exactapi
    restart: unless-stopped
    build:
      context: ./
      ssh:
        - "default"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - "EXACTAUTH_HOST=http://host.docker.internal:8081"
      - "MRAUTH_HOST=http://host.docker.internal:3444"
    ports:
      - "3445:8080"